### ISSUE TITLE
Commands expressed in text insert carriage return when wordwrapped

### ISSUE THREAD

**Issue by pmatulis** [canonical-webteam/documentation-builder#101]
When a CLI invocation is wrapped in backticks, such as \`juju blah\`, it receives a monospace font. This breaks when the command is word-wrapped. This is a significant irritant as auto-wrapped paragraphs need to constantly be edited manually. Many instances are not caught and the end result is very poor for the reader.

Is it possible for d-b to be taught how to deal with word-wrapped backticked text?

**Comment by anthonydillon** [comment]
@pmatulis thanks for filling this issue. Could you please provide an example and if be happy to adjust the word wrapping.

**Comment by pmatulis** [comment]
@anthonydillon This issue has been plaguing me for a while and I forgot the actual symptoms. I just tested it. What happens is that the formatting is indeed applied but a carriage return is inserted as well.

![wordwrapped-command-source](https://user-images.githubusercontent.com/6303808/35284544-1b09d1d8-0029-11e8-8a33-a53bcd23cc87.png)

![wordwrapped-command](https://user-images.githubusercontent.com/6303808/35284419-c320470e-0028-11e8-8006-bc995b5be5f1.png)

**Comment by anthonydillon** [comment]
Oh I see, code blocks should not wrap and scroll if required. Thanks @pmatulis.

**Comment by nottrobin** [comment]
We discussed this in a meeting with @pmahnke, @anthonydillon, @evilnick, @kwm14, @nottrobin, and agreed that it is reasonable for carriage returns to be preserved inside `code blocks`. The fix should be to reject pull requests that try to add carriage returns where they shouldn't be. Closing this now.
