### ISSUE TITLE
We should check links when building

### ISSUE THREAD

**Issue by evilnick** [canonical-webteam/documentation-builder#35]
At a minimum, it should be possible to determine that any local/relative links are valid and emit warnings if they are malformed

**Comment by nottrobin** [comment]
I think doing this at build-time might significantly increase the time it takes to build pages.

I wonder if it might be best to solve this through decent CI testing systems which will check for broken links when submitting pull requests - as tangentially mentioned in https://github.com/canonical-webteam/practices.

**Comment by evilnick** [comment]
I also now think it would be better handled by CI on the repositories. Could do with some pointers on setting that up though - documentation-builder requires one of the newer VM CI environments and python3, but linkchecker seems to be abandonware now and stuck on old versions

**Comment by nottrobin** [comment]
Yes, an example of where we do this is https://github.com/canonical-websites/developer.ubuntu.com/blob/master/.travis.yml, but that installs linkchecker from apt which may well be stale by now.

You can also pip install linkchecker, which should still work.

The original wummel/linkchecker project was abandoned, but someone forked it and I believe is actively working on it at https://github.com/linkcheck/linkchecker

**Comment by evilnick** [comment]
Thanks, I'll check that out! I think I tried the pip install before but ran into trouble with conflicting Python installs (you can only be in one env at a time).

 As this now becomes a docs repo issue, I guess we can close this one too
