### ISSUE TITLE
[wishlist] code block copy button

### ISSUE THREAD

**Issue by pmatulis** [canonical-webteam/documentation-builder#39]
It would be great to have a "copy" icon appear within a code block when the reader's mouse cursor hovers over it. [Here](https://cloud.google.com/functions/docs/tutorials/ocr) is an example.

**Comment by pmatulis** [comment]
I'm starting to experience feature-request-regret. A lot of our code blocks contain multiple commands so I'm uncertain if this feature will help or hinder.

**Comment by nottrobin** [comment]
okay I'll close it for now, we can reopen if we decide we do in fact want it. Thanks.
