### ISSUE TITLE
Make TOC display on every page

### ISSUE THREAD

**Issue by nottrobin** [canonical-webteam/documentation-builder#50]
Following on from https://github.com/ubuntudesign/vanilla-docs-theme/issues/4 - instead of making the Table of Contents optional, we should implement a standard rule that it appears when there are X or more sub-headings.

For now I'm going to go with 3 or more. This can be tweaked in the future.

**Comment by anthonydillon** [comment]
In my opinion I prefer consistency. Even if there are only two headers the user knows that before reading the content and can also get a quick mental model of the article before starting to read.

Also if the first section is very long it gives an experienced user the ability to jump to the final section which may just contain the command they are looking for.

**Comment by nottrobin** [comment]
@anthonydillon Yep I completely agree. So does @caldav. I'll do it that way then.
