### ISSUE TITLE
We should use the standard library for Admonitions instead of 'mdxCallouts' 

### ISSUE THREAD

**Issue by evilnick** [canonical-webteam/documentation-builder#62]
The Callouts extension was a hack, there is a proper Admonition library. Fortunately, because we already hacked the hack to make it work with the proper syntax, admonitions which follow style will still work with the proper extension.
The new extension does give us finer-grain control over admonitions though.

**Comment by nottrobin** [comment]
Resolved by https://github.com/canonical-webteam/documentation-builder/pull/65
