### ISSUE TITLE
Numbered lists are reset after each code block

### ISSUE THREAD

**Issue by pmatulis** [canonical-webteam/documentation-builder#79]
Numbered lists are reset after each code block:

```
1. Blah blah blah

1. Blah blah blah

> ```bash
>command1
>```

1. Blah blah blah
```

I expect
1
2
3

But I get 
1
2
1

**Comment by nottrobin** [comment]
Your initial snippet wouldn't work in any Markdown system I know of. E.g.:

---

1. Blah blah blah

> ```bash
>command1
>```

1. Blah blah blah

---

A solution that works on GitHub is to indent the code block and any other lines that are intended to be contained within a bullet point to the same level as the first word in the bullet point. e.g.:

``` markdown
1. Blah blah blah
    
    ``` bash
    a command
    ```
1. Blah blag blah
```

Which displays the way you want as:

---

1. Blah blah blah
    
    ``` bash
    a command
    ```
1. Blah blag blah

---

I'm closing this for now as I imagine this syntax will solve your problem in all contexts. Although if you find this doesn't work in `documentation-builder` please let us know.

**Comment by pmatulis** [comment]
For me, a code block will not be formatted if it is indented. Maybe it's different when actually published but locally it does not work for me.
