### ISSUE TITLE
CSS: Make the docs area fixed width 

### ISSUE THREAD

**Issue by abetkin** [canonical-webteam/documentation-builder#82]
Currently the docs area occupies all the page. That's not cool. Make it fixed-width like for example the default theme on readthedocs does.

**Comment by nottrobin** [comment]
The text area is actually already fixed-width, it's just quite wide:

![fixed-width](https://user-images.githubusercontent.com/519935/30423736-b86476b8-993b-11e7-8102-81c27cbde8b9.png)

Suggestions for design improvements should happen over in the [vanilla design repository](https://github.com/ubuntudesign/vanilla-design/issues).
