### ISSUE TITLE
Can't show a hyperlink as a hyperlink

### ISSUE THREAD

**Issue by pmatulis** [canonical-webteam/documentation-builder#83]
This [MAAS page](https://docs.ubuntu.com/maas/2.2/en/installconfig-images) uses the following [code](https://raw.githubusercontent.com/CanonicalLtd/maas-docs/master/en/installconfig-images.md):

```
[https://images.maas.io/ephemeral-v3/daily/][default-boot-source]
[default-boot-source]: https://images.maas.io/ephemeral-v3/daily/
```

The point is to have the hyperlink show up as a hyperlink. As is, just the hyperlink text shows up. Trying without the labelling gives the same result.

What I don't understand is why this works on my [local web server](http://pmatulis.maas.papamike.ca/en/installconfig-images.html).

**Comment by nottrobin** [comment]
Seems to be working now.
