### ISSUE TITLE
Multi-versioned documentation should use canonical links

### ISSUE THREAD

**Issue by evilnick** [canonical-webteam/documentation-builder#96]
...or some other way of indicating which is the preferred version.

https://support.google.com/webmasters/answer/139066?hl=en

We have this problem already with Juju, where search results rank older (sometimes archived) versions of the docs above the current version.

**Comment by nottrobin** [comment]
Agreed and added to https://github.com/ubuntudesign/vanilla-and-base-squad/issues/121 to be worked on

**Comment by evilnick** [comment]
NB - we agreed that this work should also include handling 'archive' versions of the documentation, which are published but not linked in nav.

**Comment by nottrobin** [comment]
> NB - we agreed that this work should also include handling 'archive' versions of the documentation, which are published but not linked in nav.

Yes this was mentioned in https://github.com/canonical-webteam/documentation-builder/issues/81#issuecomment-329519746 but I think it makes sense to solve it as part of this issue.

**Comment by nottrobin** [comment]
Canonical links added to maas docs in https://github.com/CanonicalLtd/maas-docs/pull/982, and released here: https://jenkins.canonical.com/webteam/job/deploy-to-docs.staging.maas.io/99/console
